### PR TITLE
Groovy dependencies definition

### PR DESCRIPTION
**Pull request by Simply007**
Shouldn't we show this syntax @aweigold?

### Motivation

I have generated a basic project using Gradle using [this tutorial](https://guides.gradle.org/building-java-applications/).

The only way to add a dependency is to use the implementation definition in dependencies.

### CODE REVIEW

**Comment by aweigold** [comment]
@Simply007 you are correct.  The reason you are running into the issue is that you are likely using Gradle 5+, when this README was made, it was using an older version of Gradle.

**Comment by Simply007** [comment]
First of all, I am not an expert in the Java world. 

Feel free to change the Readme according to your feeling of which version is more commonly used.

But from my point of view as a not experienced Java developer, it took some time when I found the cause my build is failing, so some note about the syntax difference between version would help people like me.

Pings:
* We should consider adding this info also for the quick start (ping @peterskoda, @daemoon).
* And another ping for @Neytus as Android SDK maintainer

**Comment by aweigold** [comment]
We're in full agreement.  I concur this should be updated, it's unlikely anyone would start the project with an older version of Gradle, and those bringing this into an existing project would likely know what to change.  I'll update the README when I have a chance, or if you rebase this PRs branch we should merge it in.

As far as documentation, in general, I have some changes locally for the next major version of the SDK that should greatly improve upon it.  If I had to grade the documentation as of what is currently here I'd give it a D-, someone with development experience should be able to figure this out irregardless to experience with Java.

**Comment by Simply007** [comment]
Sorry for so long delay and pell-mell commits @aweigold,

Is it OK for you now to squash and merge the pull request?

**Comment by aweigold** [comment]
No problem!  Will do that now.

**Pull request merged**
