### PR TITLE
Fix for issue #35 - Replaced ZonedDateTime for Joda's DateTime

### PR DESCRIPTION
**Pull request by luan-cestari**

### CODE REVIEW

**Comment by luan-cestari** [comment]
Fix for issue #35

**Comment by aweigold** [comment]
Hi Luan,

Thanks for the submission, this is helpful.

A couple notes:
- The unit tests do not pass with this.  I see that the CI build shows a pass, which is something I'll take a look at.
- I was hoping to see if there was a way to 'shadow' joda with the standard Java 8 java.time API, as changing the signatures on those methods would cause upgrade breaking changes to the Kentico API.  Doing some further review, it may not be simple to do with Joda.  Perhaps [this project](https://github.com/JakeWharton/ThreeTenABP) can help for inspiration?  That project does have a dependency on initializing the library like the other you found, but maybe there is a way we can fork it and grab the tzdata as a jar resource (or embed it into a generated class).

I assumed when I made this issue that this would be rather difficult.  I'm very appreciative of the work you put in, perhaps we could chat and figure out ways to flush out the issues if you are still interested in helping?

**Comment by luan-cestari** [comment]
Hi @aweigold , 

Sorry, I thought I understood the issue but now I see I don't

>I was hoping to see if there was a way to 'shadow' joda with the standard Java 8 java.time API, as changing the signatures on those methods would cause upgrade breaking changes to the Kentico API. Doing some further review, it may not be simple to do with Joda. Perhaps this project can help for inspiration? That project does have a dependency on initializing the library like the other you found, but maybe there is a way we can fork it and grab the tzdata as a jar resource (or embed it into a generated class).

To understand more the problem, may I ask some questions: 

- Does the timezone data file can be from IANA ( https://www.iana.org/time-zones ) ? (which I think is have the most accurate and the authority over the subject) Also, if we got from there, can it be outdated in the future?
- About the root cause of the issue, does using JakeWharton/ThreeTenABP library solve? Why would require to do the same code as that project instead of using as dependency? Using this library will also solve that issue you mentioned about Duration on Android version 26?
- About not breaking the API, does that means that it will still receive ZonedDateTime but then it will transform in another object from a library that support JSR-310 ?

**Comment by aweigold** [comment]
@luan-cestari , no apologies necessary, I did a poor job with the original issue write up.

> Does the timezone data file can be from IANA ( https://www.iana.org/time-zones ) ? (which I think is have the most accurate and the authority over the subject) Also, if we got from there, can it be outdated in the future?

It could become outdated, but we can maintain that along with the project.  Given the consumers I know of with this project, a short delay in the latest timezone info would likely be more than fine.

> About the root cause of the issue, does using JakeWharton/ThreeTenABP library solve? Why would require to do the same code as that project instead of using as dependency? Using this library will also solve that issue you mentioned about Duration on Android version 26?

The JakeWharton library grabs the tzdata as an android resource from the context, and then loads up another library to provide the JSR-310 implementation.  I'm wondering if it's possible to just load the tzdata as a resource from the jar, or some other solution, as not to put a requirement to initialize it specifically.  If it's not possible, then this SDK should have it's own initializer that will bootstrap it (there is already an init function inside of DeliveryClient to init some Jackson modules), and we would have to work on the build to ensure that android is not depended on in the java version.  (the current build shares the same sources as the java sdk).

> About not breaking the API, does that means that it will still receive ZonedDateTime but then it will transform in another object from a library that support JSR-310 ?

Correct.

**Comment by luan-cestari** [comment]
Hi @aweigold ,

Why is necessary the JSR-310 compatibility? Is it required due jackson? Is there some other reasons? 

I did some research, that other project https://github.com/ThreeTen/threetenbp is not an implementation of JSR-310, only backport to legacy applications. Which is also states in https://stackoverflow.com/questions/42056336/get-string-date-from-millis-with-api-level-15-with-right-locale-and-24h .

If I got the problem you mentioned in the issue correctly, the ZonedDateTime started to be available in API level 26  (as mentioned in javadocs https://developer.android.com/reference/java/time/ZonedDateTime.html  ). As the SDK can have legacy clients (API level < 26) it would need a solution for that, which you mention to "shadow", for example. I can only see change the API and using the ThreeTen project to make legacy clients possible. I know it breaks the API as it changes, but it will start to work to legacy applications and the current clients will also work with this new solution. What do you think?

**Comment by aweigold** [comment]
When I say, "shadow", I mean to take the classes that implement the standard, and update the shadow plugin in the gradle file to add them.

I can explain further with an example of where this is already used in the build.

If you take a look at this snippet from the gradle file:
```
shadowJar {
    baseName = 'delivery-sdk-android'
    version = project.version
    classifier = null
    relocate 'org.apache.http', 'shadow.kentico.http'
}
```

What that does, is tells the gradle shadow plugin (which only is applied to the android build) to take any classes in `org.apache.http` and place them in `shadow.kentico.http`.  It also goes through any references to those classes, and rewrites the import.  In this particular case, we are doing this due to apache httpcomponents already being provided by Android, albeit an out of date version that is not compatible with the rest of the SDK.  Updating the references allows us to include our own library, without breaking the java-sdk api, or conflicting with androids org.apache.http package.  The shadowing only happens on the android build of this SDK.

In theory (although this whole issue is just an investigation at this point), we should be able to provide classes that provide some sort of implementation for for the JSR-310* java.time api referenced in some of these classes.  We would simply only include that library only in the android build, and then use the shadow plugin to make sure it doesn't conflict (as API 26 would) into `shadow.kentico.time`.  All the while, not breaking the API the Java consumers of the SDK are using.

I had thought that joda was close enough to the java.time spec, given that the java.time spec was based on it, however that doesn't seem to be the case after digging in a bit.  I'm unsure if the library I pointed out will work (if I did, that means I would have had the time to implement and close the issue myself :-) ), but if it provides a reasonable backport to java.time, we could configure the build to shadow it to a different namespace, and thus allow us to continue to try to decrement the Android API requirement without breaking the Java API the SDK provides.

* I should note, we may not need a full implementation of JSR-310... just enough for the ZonedDateTime classes to work.

**Comment by luan-cestari** [comment]
I didn't know that plugin. Thank you for the explanation. I read the documentation of it ( http://imperceptiblethoughts.com/shadow/#relocating_packages ) , especially the part 

> Shadow uses the ASM library to modify class byte code to replace the package name and any import statements for a class

I didn't test but so far as I understand, if the bytecode definition changed to use the relocated ( ZonedDateTime in our case with a new package  ) it would mean that the API changed. For example, a client would new to pass *shadow.kentico.time.ZonedDateTime* instead *java.time.ZonedDateTime* as  before. Do you also think that will happens?

**Comment by luan-cestari** [comment]
A possible workaround could be creating a checking the presence of the ZonedDateTime using something like Class.forName("java.time.ZonedDateTime"), or other reflection feature.  If not exception is caught, it use the current API and if it throws a class not found it would could do something about it. Maybe it could use a whole different internal classes (all the classes that use ZonedDateTime and the one that invoke that one and etc) and still have a problem which the change in the API in the end so I would exclude this possibility . But, another possibility if caught the exception, we could load another ZonedDateTime class definition during the runtime (I don't know if Android would allow this kind of thing). In both cases I'm avoid to have duplicated ZonedDateTime class definition in runtime on propose as it could lead others problems for Android API level > 25.

If this idea for workaround works, the remaining problem would have a replacement for ZonedDateTime during the runtime as it is from Java source and have copyright http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/time/ZonedDateTime.java  . Threeten  also have copyright https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/ZonedDateTime.java

**Comment by aweigold** [comment]
Glad you are following me now, sorry for the lack of explanation in the original issue.

You are correct, shadowing does change the bytecode definition, and would change the API, that said, it would only change the API for the jar used for android, and that isn't finalized yet (still experimental).

As far as the conditional class check, I'm fine with that, and we are actually doing that in the SDK to search for Thymeleaf... but there will be additional work to get the jackson bindings functioning if we take that approach.

As far as copyright, Threeten is BSD licensed (https://github.com/ThreeTen/threetenbp/blob/master/LICENSE.txt), so it should be permissible to derive from that.  The openjdk version is GNU.

**Comment by aweigold** [comment]
We are going to remove support for android in this sdk in version 2.0 in lieu of using a separately developed SDK.  As thus, I'm going to close this PR.  Thanks for the help everyone!.

**Pull request closed without merging**
