### PR TITLE
Options values

### LINKED ISSUE #23: Strongly Typed Content Item Converter does not support mapping name from an Option
If an Option is mapped to a field, the name from the option should be used.

### PR DESCRIPTION
**Pull request by cunhazera**
Fixes #23

Is it what you guys mean?

### CODE REVIEW

**Comment by cunhazera** [comment]
@Simply007 oh, that's great! Second year in a row :)

I have just filled the form.

**Comment by makma** [comment]
Is this still valid? Are you guys going to finish this one? Thanks.

**Comment by cunhazera** [comment]
@Simply007 I'm sorry to tell you, but one year has gone and the postal service from Brazil did not deliver what you sent.

**Comment by Simply007** [comment]
@cunhazera - I am sorry about it. It is hard to handle all of the packages. We had some issues with delivering packages out of the continent. 

Is there any chance you are visiting the Czech Republic?

**Comment by cunhazera** [comment]
@Simply007 no chance :(

**Pull request closed without merging**
