### PR TITLE
#53 Implement optional retry logic for CDN failures

### PR DESCRIPTION
**Pull request by aweigold**
Here is an implementation for retrying requests on failures.  By default, no retries are performed.  When a retry is performed, there is a binary backoff based on 100ms to the API.

Could you guys give this a quick glance?

### CODE REVIEW

**Comment by petrsvihlik** [comment]
@JanLenoch could you please have a look at it?

**Comment by JanLenoch** [comment]
Hi @aweigold , great job! I like that you've done a perfect compromise between complexity and automation in the exponential retry timeout calculation (simply calculate a power of 2). Your implementation goes along with the general recommendation that I've read about at https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#general-rest-and-retry-guidelines and https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults#general-guidelines .

I'd adopt this approach in our other SDK. Do you agree, @petrsvihlik ?

**Comment by petrsvihlik** [comment]
@JanLenoch yes, I agree.

**Comment by aweigold** [comment]
@JanLenoch Thanks!  It was just habit from my previous gig, where we always did that based on Microsoft's advice everywhere. :-)

**Pull request merged**
